---
Packaging:
  pomVersion: 0.9.3
  isDeveloper: false
  isDevelopment: true
  isProduction: false
  time_zone: Eastern Time (US & Canada)

PostgreSQL:
  username: postgres
  password: postgres
  host: localhost

remote_log:
  hostname: localhost
  port: 8071

access_profile:
  default_unknown_to_unsecure: false
  options_keyword: options
  access_registry_filename:  # defaults to <root>/config  -- no override
    basename: access_registry
    extension: xml
  content_registry_filename:  # defaults to <root>/config  -- no override
    basename: content_registry
    extension: xml

security:
  admin_role: Services.Action.Admin
  extra_digest_strength: 3
  session_expires: 160
  remembered_for:  720
  verify_login_after_seconds: 28800   # 8 hours
  ! public_pages: # no easily stored in the xml, because of leading slash
   - /assets

  ! user_options:
   - Manager
   - Developer
   - EmployeePrimary
   - EmployeeSecondary
   - BranchPrimary
   - BranchSecondary
   - VendorPrimary
   - VendorSecondary
   - '0034'
   - '0037'
   - '0040'
   - '1601'
   - '1602'
   - '0099'
