---
Packaging:
  pomVersion: 0.2.2
  isDeveloper: false
  isDevelopment: true
  isProduction: false
  time_zone: Eastern Time (US & Canada)

PostgreSQL:
  username: postgres
  password: postgres
  host: localhost

remote_log:
  hostname: localhost
  port: 8071

security:
  admin_role: EmployeePrimary
  verify_login_after_msecs: 7200000

standards:
  ! security_roles:
    - InsuredSecondary
    - InsuredPrimary
    - AgentSecondary
    - AgentPrimary
    - EmployeeAgencySecondary
    - EmployeeAgencyPrimary
    - EmployeeSecondary
    - EmployeePrimary
  ! role_groups:
    - AgencyStaff
    - InsuredStaff
    - InternalStaff
