---
Packaging:
  pomVersion: 0.2.2
  isDeveloper: false
  isDevelopment: true
  isProduction: false
  time_zone: Eastern Time (US & Canada)

PostgreSQL:
  username: postgres
  password: postgres
  host: localhost

remote_log:
  hostname: localhost
  port: 8071

access_profile:
  default_unknown_to_unsecure: false
  options_keyword: options
  registry_filename:  # defaults to <root>/config  -- no override
    basename: access_registry
    extension: xml

security:
  admin_role: Services.Action.Admin
  extra_digest_strength: 3
  session_expires: <%= -> { 4.hours.from_now } %>
  remembered_for:  <%= -> { 12.hours.from_now } %>
  verify_login_after_msecs: 28800000   # 8 hours
  ! public_pages:
   - /signout
   - /signin
   - /home
   - /about
   - /learn_more
   - /details_model
   - /details_content
   - /details_access
   - details_auth
   - /assests
   - /unauthenticated
   - /sessions
   - sessions/new
   - sessions/create
