---
Packaging:
  isTest: false
  isDevelopment: true
  isProduction: false

PostgreSQL:
  username: postgres
  password: postgres
  host: localhost


security:
  session_expires: 60
  remembered_for:  120
  verify_login_after_seconds: 360   # 5 minutes
