---
Packaging:
  isTest: false
  isDevelopment: true
  isProduction: false

PostgreSQL:
  username: postgres
  password: postgres
  host: localhost


security:
  session_expires: 1280
  remembered_for:  14400
  verify_login_after_seconds: 360   # 5 minutes
