---
Packaging:
  isTest: true
  isDevelopment: false
  isProduction: false

rspec_users:
  password: developer99
  manager: manager1
  staff: staff1
  support: support1

security:
  session_expires: 240
  remembered_for:  720
